spring:
  datasource:
    url: jdbc:mysql://localhost:3306/PPDB_DB
    username: root
    password: Akbar_123
    hikari:
      connection-timeout: 3000
      maximum-pool-size: 10
      minimum-idle: 4
      idle-timeout: 600000
      pool-name: PPDB Application Pool
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    database: mysql

application:
  version: 1
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
